# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "ubuntu/trusty64"


  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
  end
  config.vm.network "forwarded_port", guest: 22, host:3022, auto_correct: true
  config.vm.network "forwarded_port", guest: 8030, host:8030, auto_correct: true
  config.vm.network "forwarded_port", guest: 8031, host:8031, auto_correct: true
  config.vm.network "forwarded_port", guest: 8032, host:8032, auto_correct: true
  config.vm.network "forwarded_port", guest: 8033, host:8033, auto_correct: true
  config.vm.network "forwarded_port", guest: 8040, host:8040, auto_correct: true
  config.vm.network "forwarded_port", guest: 8042, host:8042, auto_correct: true
  config.vm.network "forwarded_port", guest: 8088, host:8088, auto_correct: true
  config.vm.network "forwarded_port", guest: 49707, host:49707, auto_correct: true
  config.vm.network "forwarded_port", guest: 50010, host:50010, auto_correct: true
  config.vm.network "forwarded_port", guest: 50020, host:50020, auto_correct: true
  config.vm.network "forwarded_port", guest: 50070, host:50070, auto_correct: true
  config.vm.network "forwarded_port", guest: 50075, host:50075, auto_correct: true
  config.vm.network "forwarded_port", guest: 50090, host:50090, auto_correct: true
  config.vm.provision :docker
  config.vm.provision :docker_compose, yml: "/vagrant/docker-compose.yml", run: "always", rebuild: true
end
